apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  # deployment labels
  labels:
    component: mongodb  
    project: roboshop 
    tier: database
spec:
  replicas: 1
# These are the labels replica set use to create pod replicas, This should match pod labels.
  selector:
    matchLabels:
      component: mongodb  
      project: roboshop 
      tier: database
  template:
  # This pod defination
    metadata:
      labels:
        component: mongodb  
        project: roboshop 
        tier: database
    spec:
      containers:
      - name: mongodb
        image: sriharibandidevops/mongodb:v1